apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: pristinewebdev-com-tls
spec:
  secretName: pristinewebdev-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: pristinewebdev.com
  dnsNames:
    - pristinewebdev.com
    - www.pristinewebdev.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - pristinewebdev.com
          - www.pristinewebdev.com
